### ISSUE TITLE
Embellish README

### ISSUE THREAD

**Issue by blaino** [nissint/graceland#7]
It would be nice if you had a section showing a) how it used to be done and b) how it's done with graceland.

**Comment by colemanserious** [comment]
Partial help from a user of Graceland hoping to help another user: For the how it's done - take a look at test/graceland.spec.js

**Comment by qtpeters** [comment]
Thanks! I'll get on it!

**Comment by qtpeters** [comment]
README Embellished, good suggestion.  Will somebody look it over for mistakes? Thanks!
